name: Build

on: push

jobs:
  build_windows:
    name: Windows
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: Checkout Repository
        id: repo-check
        uses: actions/checkout@v6

      - name: Install Haxe
        id: haxe-install
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Restore Cache
        id: cache-restore
        uses: actions/cache/restore@v5
        with:
          key: cache_windows
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/

      - name: Install / Update Libraries
        id: lib-install
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          haxelib install hxpkg
          haxelib run hxpkg install

      - name: Set up HXCPP
        id: setup-hxcpp
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          cd ./.haxelib/hxcpp/git/tools/hxcpp/
          haxe compile.hxml
          cd ../../../../../

      - name: Rebuild Lime Tools
        id: fix-lime
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          cd ./.haxelib/lime/git/
          git submodule init
          git submodule sync
          git submodule update
          cd ../../../
          haxelib run lime rebuild cpp

      - name: Build Game
        id: game-compile
        run: |
          haxelib run lime build windows -release

      - name: Upload Artifact
        id: artifact-upload
        uses: actions/upload-artifact@v6
        with:
          name: VS IMPOSTOR Pixel (Windows)
          path: export/release/windows/bin/

      - name: Clear old Cache
        id: cache-clear
        uses: actions/github-script@v8
        if: steps.cache-restore.outputs.cache-hit == 'true'
        with:
          script: |
            const caches = github.rest.actions.deleteActionsCacheByKey({
              owner: context.repo.owner,
              repo: context.repo.repo,
              key: "cache_windows"
            });

      - name: Save new Cache
        id: cache-save
        uses: actions/cache/save@v5
        with:
          key: cache_windows
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/

  build_linux:
    name: Linux
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repository
        id: repo-check
        uses: actions/checkout@v6

      - name: Install Haxe
        id: haxe-install
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Restore Cache
        id: cache-restore
        uses: actions/cache/restore@v5
        with:
          key: cache_linux
          path: |
            .haxelib/
            export/release/linux/haxe/
            export/release/linux/obj/

      - name: Install Packages
        id: packages-install
        run: |
          sudo apt-get update
          sudo apt-get install libvlc-dev libvlccore-dev libvlccore9
          sudo apt-get install -qq \
          libegl1-mesa-dev libgl1-mesa-dev libibus-1.0-dev libdbus-1-dev libdecor-0-dev libudev-dev libgbm-dev libdrm-dev \
          libpng-dev libturbojpeg-dev libvorbis-dev libopenal-dev libsdl2-dev libglu1-mesa-dev libmbedtls-dev libuv1-dev libsqlite3-dev \
          libx11-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbcommon-dev libxcursor-dev libxrandr-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxxf86vm-dev \
          libpulse-dev libasound2-dev libpipewire-0.3-dev \
          g++-multilib gcc-multilib

      - name: Install / Update Libraries
        id: lib-install
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          haxelib install hxpkg
          haxelib run hxpkg install

      - name: Set up HXCPP
        id: setup-hxcpp
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          cd ./.haxelib/hxcpp/git/tools/hxcpp/
          haxe compile.hxml
          cd ../../../../../

      - name: Rebuild Lime Tools
        id: fix-lime
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          cd ./.haxelib/lime/git/
          git submodule init
          git submodule sync
          git submodule update
          cd ../../../
          haxelib run lime rebuild cpp

      - name: Build Game
        id: game-compile
        run: |
          haxelib run lime build linux -release

      - name: Upload Artifact
        id: artifact-upload
        uses: actions/upload-artifact@v6
        with:
          name: VS IMPOSTOR Pixel (Linux)
          path: export/release/linux/bin/

      - name: Clear old Cache
        id: cache-clear
        uses: actions/github-script@v8
        if: steps.cache-restore.outputs.cache-hit == 'true'
        with:
          script: |
            const caches = github.rest.actions.deleteActionsCacheByKey({
              owner: context.repo.owner,
              repo: context.repo.repo,
              key: "cache_linux"
            });

      - name: Save new Cache
        id: cache-save
        uses: actions/cache/save@v5
        with:
          key: cache_linux
          path: |
            .haxelib/
            export/release/linux/haxe/
            export/release/linux/obj/

  build_mac:
    name: macOS
    runs-on: macos-latest
    permissions: write-all
    steps:
      - name: Checkout Repository
        id: repo-check
        uses: actions/checkout@v6

      - name: Install Haxe
        id: haxe-install
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Restore Cache
        id: cache-restore
        uses: actions/cache/restore@v5
        with:
          key: cache_mac
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/

      - name: Install / Update Libraries
        id: lib-install
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          haxelib install hxpkg
          haxelib run hxpkg install

      - name: Set up HXCPP
        id: setup-hxcpp
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          cd ./.haxelib/hxcpp/git/tools/hxcpp/
          haxe compile.hxml
          cd ../../../../../

      - name: Rebuild Lime Tools
        id: fix-lime
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          cd ./.haxelib/lime/git/
          git submodule init
          git submodule sync
          git submodule update
          cd ../../../
          haxelib run lime rebuild cpp

      - name: Build Game
        id: game-compile
        run: |
          haxelib run lime build mac -release

      - name: Upload Artifact
        id: artifact-upload
        uses: actions/upload-artifact@v6
        with:
          name: VS IMPOSTOR Pixel (macOS)
          path: export/release/macos/bin/

      - name: Clear old Cache
        id: cache-clear
        uses: actions/github-script@v8
        if: steps.cache-restore.outputs.cache-hit == 'true'
        with:
          script: |
            const caches = github.rest.actions.deleteActionsCacheByKey({
              owner: context.repo.owner,
              repo: context.repo.repo,
              key: "cache_mac"
            });

      - name: Save new Cache
        id: cache-save
        uses: actions/cache/save@v5
        with:
          key: cache_mac
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/

  build_html5:
    name: HTML5 (Web)
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repository
        id: repo-check
        uses: actions/checkout@v6

      - name: Install Haxe
        id: haxe-install
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Restore Cache
        id: cache-restore
        uses: actions/cache/restore@v5
        with:
          key: cache_html5
          path: |
            .haxelib/
            export/release/html5/haxe/
            export/release/html5/obj/

      - name: Install Packages
        id: packages-install
        run: |
          sudo apt-get update
          sudo apt-get install libvlc-dev libvlccore-dev libvlccore9
          sudo apt-get install -qq \
          libegl1-mesa-dev libgl1-mesa-dev libibus-1.0-dev libdbus-1-dev libdecor-0-dev libudev-dev libgbm-dev libdrm-dev \
          libpng-dev libturbojpeg-dev libvorbis-dev libopenal-dev libsdl2-dev libglu1-mesa-dev libmbedtls-dev libuv1-dev libsqlite3-dev \
          libx11-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbcommon-dev libxcursor-dev libxrandr-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxxf86vm-dev \
          libpulse-dev libasound2-dev libpipewire-0.3-dev \
          g++-multilib gcc-multilib

      - name: Install / Update Libraries
        id: lib-install
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          haxelib install hxpkg
          haxelib run hxpkg install

      - name: Set up HXCPP
        id: setup-hxcpp
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          cd ./.haxelib/hxcpp/git/tools/hxcpp/
          haxe compile.hxml
          cd ../../../../../

      - name: Rebuild Lime Tools
        id: fix-lime
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          cd ./.haxelib/lime/git/
          git submodule init
          git submodule sync
          git submodule update
          cd ../../../
          haxelib run lime rebuild cpp

      - name: Build Game
        id: game-compile
        run: |
          haxelib run lime build html5 -release

      - name: Upload Artifact
        id: artifact-upload
        uses: actions/upload-artifact@v6
        with:
          name: VS IMPOSTOR Pixel (HTML5)
          path: export/release/html5/bin/

      - name: Clear old Cache
        id: cache-clear
        uses: actions/github-script@v8
        if: steps.cache-restore.outputs.cache-hit == 'true'
        with:
          script: |
            const caches = github.rest.actions.deleteActionsCacheByKey({
              owner: context.repo.owner,
              repo: context.repo.repo,
              key: "cache_html5"
            });

      - name: Save new Cache
        id: cache-save
        uses: actions/cache/save@v5
        with:
          key: cache_html5
          path: |
            .haxelib/
            export/release/html5/haxe/
            export/release/html5/obj/

  build_android:
    name: Android
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repository
        id: repo-check
        uses: actions/checkout@v6

      - name: Install Java JDK
        id: jdk-install
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Install Android SDK
        id: sdk-install
        uses: android-actions/setup-android@v3.2.2

      - name: Install Android NDK
        id: ndk-install
        uses: nttld/setup-ndk@v1.6.0
        with:
          ndk-version: r29

      - name: Install Haxe
        id: haxe-install
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Restore Cache
        id: cache-restore
        uses: actions/cache/restore@v5
        with:
          key: cache_android
          path: |
            .haxelib/
            export/release/android/haxe/
            export/release/android/obj/

      - name: Install Packages
        id: packages-install
        run: |
          sudo apt-get update
          sudo apt-get install libvlc-dev libvlccore-dev libvlccore9
          sudo apt-get install -qq \
          libegl1-mesa-dev libgl1-mesa-dev libibus-1.0-dev libdbus-1-dev libdecor-0-dev libudev-dev libgbm-dev libdrm-dev \
          libpng-dev libturbojpeg-dev libvorbis-dev libopenal-dev libsdl2-dev libglu1-mesa-dev libmbedtls-dev libuv1-dev libsqlite3-dev \
          libx11-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbcommon-dev libxcursor-dev libxrandr-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxxf86vm-dev \
          libpulse-dev libasound2-dev libpipewire-0.3-dev \
          g++-multilib gcc-multilib

      - name: Install / Update Libraries
        id: lib-install
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          haxelib install hxpkg
          haxelib run hxpkg install

      - name: Set up Android
        id: setup-android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT ${{ steps.ndk-install.outputs.ndk-path }}
          haxelib run lime config JAVA_HOME ${{ env.JAVA_HOME }}
          haxelib run lime config ANDROID_SETUP true
          haxelib run lime setup android -alias -y -nocffi -eval

      - name: Set up HXCPP
        id: setup-hxcpp
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          cd ./.haxelib/hxcpp/git/tools/hxcpp/
          haxe compile.hxml
          cd ../../../../../

      - name: Rebuild Lime Tools
        id: fix-lime
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          cd ./.haxelib/lime/git/
          git submodule init
          git submodule sync
          git submodule update
          cd ../../../
          haxelib run lime rebuild cpp
          haxelib run lime rebuild android

      - name: Build Game
        id: game-compile-lime
        run: |
          haxelib run lime build android -release

      - name: Build APK
        id: game-compile-gradle
        run: |
          chmod +x export/release/android/bin/gradlew

          cd export/release/android/bin/
          ./gradlew clean
          ./gradlew assembleDebug
          cd ../../../../

      - name: Upload Artifact
        id: artifact-upload
        uses: actions/upload-artifact@v6
        with:
          name: VS IMPOSTOR Pixel (Android)
          path: export/release/android/bin/app/build/outputs/apk/debug/

      - name: Clear old Cache
        id: cache-clear
        uses: actions/github-script@v8
        if: steps.cache-restore.outputs.cache-hit == 'true'
        with:
          script: |
            const caches = github.rest.actions.deleteActionsCacheByKey({
              owner: context.repo.owner,
              repo: context.repo.repo,
              key: "cache_android"
            });

      - name: Save new Cache
        id: cache-save
        uses: actions/cache/save@v5
        with:
          key: cache_android
          path: |
            .haxelib/
            export/release/android/haxe/
            export/release/android/obj/
